server.port=8085
spring.application.name=cloudbox

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cloudbox}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:akashjayaraj}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true